### ISSUE TITLE
Aishimai IV

### ISSUE THREAD

**Issue by Cosetto** [TesterTesterov/AI6WINArcTool#1]
Can you take a look at [this one](https://vndb.org/v14826) script, some of the scripts can't be inserted like sis4_00_prologue.mes and when choosing extract directory it gave error too. I tested on Biniku no Kaori, it works fine for Elf's ai6win I think?
[Aishimai.zip](https://github.com/TesterTesterov/AI6WINArcTool/files/7788060/Aishimai.zip)

**Comment by Cosetto** [comment]
Ah wrong one

**Comment by TesterTesterov** [comment]
On which Biniku no Kaori did you test (Bangai Hen or Netori Netorare Yari Yarare)?

===
"Wrong one"? So there are no problem with Aishimai 4 script or what?
