### ISSUE TITLE
Ai shimai IV encrypted cg files

### ISSUE THREAD

**Issue by IdleFishEngineer** [TesterTesterov/AI6WINArcTool#2]
Thanks for your tool! 
I unpacked the layer.arc of the game into a folder with this tool, but didn't find any picture files such as png or jpg in it,i just get many files with suffix "akb" and can't be open by any image viewer.
Never seen thease kind of files before, i think it's probablly encrypted data and i don't know how to decrypt.
Can you provide any solutions?

**Comment by TesterTesterov** [comment]
Oh, AI6WIN has the same AKB as in Silky Engine, as far as I remember. The solution to it is written in [one of the articles of mine](https://anivisual.net/blog/2020-05-27-633). (You need to find AkbTool.exe for it).

**Comment by TesterTesterov** [comment]
As the article mention the tool to deal with AKB, I close the issue.

**Comment by IdleFishEngineer** [comment]
Sorry for not response for a long time(busy for work:<),i ve read your article(the article is good.),find the AkbTool you mentioned,but seems have been locked, ive send a request(content is my user name:idleFish),so please can you let me have a copy?many thanks.

**Comment by TesterTesterov** [comment]
@IdleFishEngineer, that was not my Google Disk, so I can not restore the Silky tools. _Seems, the tool was lost, like many other good ones..._

...That is I wanted to say, but actually there was the tool on my computer. [Here you are](https://disk.yandex.ru/d/092y9SAWXXFp9A).

**Comment by IdleFishEngineer** [comment]
Thank you very much,it actually works.
