### ISSUE TITLE
Cannot unpack .arc files from Wakazuma Mangekyou + Otto no Mae Remake Edition

### ISSUE THREAD

**Issue by imouto1994** [TesterTesterov/AI6WINArcTool#3]
Hi @TesterTesterov , I have been successfully using this unpack tool for other AI6WIN titles from elf. But for this remake release combination of the two old games Wakazuma Mangekyou and Otto no Mae, the tool threw an error when I was trying to unpack the `mes.arc` file.

https://vndb.org/r4749

**Comment by imouto1994** [comment]
Please let me know if you need me to share the `mes.arc` file from this release for further debugging? 🙏

**Comment by TesterTesterov** [comment]
@imouto1994, yes, share it here. I shall look into it. Though, I don't sure if it is really AI6WIN's archive. There is one different engine, with which AI6WIN is easily confused.

**Comment by imouto1994** [comment]
Hi @TesterTesterov , below is the `mes.arc` file:
https://drive.google.com/file/d/16hCZbP42dRTcuidgPjHEL4urGGH-Mgyu/view?usp=sharing
Thank you so much for looking into this!

**Comment by TesterTesterov** [comment]
@imouto1994, hello. It is AI6WIN's archive indeed. There was a bug with more deep-rooted files.

Try [1.1 release](https://github.com/TesterTesterov/AI6WINArcTool/releases/tag/1.1) and write the results.

**Comment by imouto1994** [comment]
Hi @TesterTesterov , it worked perfectly with the new 1.1 version! Thank you so much!

![Untitled](https://user-images.githubusercontent.com/6555488/223678203-992e68ed-a94e-4f1e-a7bd-2644daff70e1.jpg)
